### ISSUE TITLE
Ubable to run start.sh

### ISSUE THREAD

**Issue by merlin123h** [p3nt4/Nuages#13]
Hi
I want to run start.sh after setup.sh command. As detailed below in attachment, I
 can't run start.sh command.

Please guide me how to run start.sh command.
Thanks.

![11](https://user-images.githubusercontent.com/67941449/109496681-d6cca500-7a45-11eb-91b2-a6f2407de7b4.PNG)

**Comment by p3nt4** [comment]
I can't see any errors in this screenshot, can you try running the two
commands of the script individually?

**Comment by merlin123h** [comment]
Dear @p3nt4 
In this picture it is shown.
Thanks

![ffff](https://user-images.githubusercontent.com/67941449/109502413-c91b1d80-7a4d-11eb-97a3-b8c8ca5ba8a6.PNG)

**Comment by p3nt4** [comment]
Hi,

This is a generic warning message, I also get it and it works fine on my
end. I can try to fix it though and we can see if it works.

Cheers,

**Comment by p3nt4** [comment]
I have removed that warning, you can try again.

**Comment by merlin123h** [comment]
Thank you

**Comment by p3nt4** [comment]
Were you able to run it?
