### ISSUE TITLE
!login invalid issue

### ISSUE THREAD

**Issue by senhaxor** [p3nt4/Nuages#29]
Hi i have setup on my kali and i started the server and client , when i try to !login i get this error

[Error] Timeout of 5000ms exceeded calling create on authentication

username and password is correct and i even tried the fix from the previous issue like changing the username to \\username and it still does not help.

Can you please help me resolving this issue

**Comment by p3nt4** [comment]
Looks like your server is not running. Did you run start.sh?

**Comment by senhaxor** [comment]
server is up and running

**Comment by p3nt4** [comment]
`[Error] Timeout of 5000ms exceeded calling create on authentication`

This error means that your client is unable to reach the server. 

Are you running the client and server on the same host?

If not, you can edit the config/production.js file to listen on 0.0.0.0. But be carefull if you are going to do it over the internet.

**Comment by gladzr** [comment]
Hi,

I am facing the same issue, and I have the start.sh script running as well. I am running it on the same host as well. Can you help me solve this issue
![image](https://user-images.githubusercontent.com/102950280/164768724-5db19c66-0a68-4b8c-9157-57a13d31a698.png)

**Comment by p3nt4** [comment]
I cant reproduce on my Kali. I will install Kali 2022 and see if I get the same error.

Your mongo database was running too?

**Comment by p3nt4** [comment]
I could not reproduce the error on a fresh Kali 2022 install. 

When you started your client, did you provide any arguments?

**Comment by gladzr** [comment]
Hi, yup mongo is running as well. I used "node nuages_cli.js"

**Comment by p3nt4** [comment]
`curl -v -X POST http://127.0.0.1:3030/authentication -H 'Content-Type: application/json' -d '{"username":"username","password":"password", "strategy":"local"}'
`
What happens when you run this?

**Comment by gladzr** [comment]
![image](https://user-images.githubusercontent.com/102950280/164787247-69003433-08a1-4abc-8404-9ec0de66ed7c.png)

This was the output, so curl works fine.

**Comment by p3nt4** [comment]
Yes looks like its working perfectly. 
Did it take more than 5 second by any chance?

**Comment by p3nt4** [comment]
I think you could try to setup an invisible proxy using Burp to look at the traffic between the client and the server. That might help you see where the error is coming from.

**Comment by gladzr** [comment]
Nope, it ran almost immediately. Yea sure, I l try with Burp and update.

**Comment by p3nt4** [comment]
In case the timeout was too short for your system for some reason, you could try to modify line 26 of nuagesAPI.js to something like:

`
app.configure(feathers.socketio(socket, {
  timeout: 10000
}));
`

Otherwise let me know how it goes with Burp.

**Comment by gladzr** [comment]
Oh! it worked. Modified as you mentioned.
Thanks

**Comment by p3nt4** [comment]
Awesome - I wonder why it takes that long. 

Keep me posted if you find the client unresponsive due to long delays like this one.

**Comment by p3nt4** [comment]
https://github.com/p3nt4/Nuages/commit/858d4cc1e24ebdfeb73d80909fddc8bad65208ee
